"""Top 20 Deloitte client archetypes for synthetic data generation.

Each company is anonymized but based on real public Deloitte relationships.
The data here is the "seed" that drives profile and posting generation.
"""

COMPANIES = [
    {
        "id": "meridian-insurance",
        "name": "Meridian Insurance Group",
        "inspired_by": "MetLife",
        "industry": "Insurance / Financial Services",
        "headcount": 45000,
        "hq": "New York, NY",
        "segments": ["Life Insurance", "Group Benefits", "Retirement Solutions", "Investment Management"],
    },
    {
        "id": "atlas-motors",
        "name": "Atlas Motors Corporation",
        "inspired_by": "General Motors",
        "industry": "Automotive / Manufacturing",
        "headcount": 155000,
        "hq": "Detroit, MI",
        "segments": ["EV Division", "ICE Vehicles", "Autonomous", "Financial Services", "Parts & Accessories"],
    },
    {
        "id": "helix-pharma",
        "name": "Helix Pharmaceuticals",
        "inspired_by": "Johnson & Johnson",
        "industry": "Pharmaceuticals / Healthcare",
        "headcount": 130000,
        "hq": "New Brunswick, NJ",
        "segments": ["Pharmaceuticals", "Medical Devices", "Consumer Health", "R&D"],
    },
    {
        "id": "velocity-logistics",
        "name": "Velocity Logistics International",
        "inspired_by": "FedEx",
        "industry": "Logistics / Transportation",
        "headcount": 500000,
        "hq": "Memphis, TN",
        "segments": ["Express", "Ground", "Freight", "Supply Chain", "Technology"],
    },
    {
        "id": "summit-hospitality",
        "name": "Summit Hospitality Group",
        "inspired_by": "Hilton",
        "industry": "Hospitality / Hotels",
        "headcount": 160000,
        "hq": "McLean, VA",
        "segments": ["Luxury", "Full Service", "Focused Service", "Timeshare", "Managed Properties"],
    },
    {
        "id": "pinnacle-health",
        "name": "Pinnacle Health Systems",
        "inspired_by": "HCA Healthcare",
        "industry": "Healthcare / Hospital Systems",
        "headcount": 280000,
        "hq": "Nashville, TN",
        "segments": ["Acute Care Hospitals", "Outpatient Centers", "Physician Staffing", "IT Services"],
    },
    {
        "id": "cardinal-energy",
        "name": "Cardinal Energy Partners",
        "inspired_by": "ExxonMobil",
        "industry": "Energy / Oil & Gas",
        "headcount": 62000,
        "hq": "Houston, TX",
        "segments": ["Upstream", "Downstream", "Chemical", "LNG", "Low Carbon Solutions"],
    },
    {
        "id": "nexus-telecom",
        "name": "Nexus Telecommunications",
        "inspired_by": "Verizon",
        "industry": "Telecommunications",
        "headcount": 115000,
        "hq": "New York, NY",
        "segments": ["Consumer Wireless", "Business Solutions", "Network Engineering", "Media", "5G/Edge"],
    },
    {
        "id": "fortress-bank",
        "name": "Fortress National Bank",
        "inspired_by": "JPMorgan Chase",
        "industry": "Banking / Financial Services",
        "headcount": 290000,
        "hq": "New York, NY",
        "segments": ["Consumer Banking", "Investment Banking", "Asset Management", "Commercial Banking", "Technology"],
    },
    {
        "id": "titan-aerospace",
        "name": "Titan Aerospace & Defense",
        "inspired_by": "Lockheed Martin",
        "industry": "Aerospace & Defense",
        "headcount": 116000,
        "hq": "Bethesda, MD",
        "segments": ["Aeronautics", "Missiles & Fire Control", "Rotary & Mission Systems", "Space"],
    },
    {
        "id": "harvest-foods",
        "name": "Harvest Foods Corporation",
        "inspired_by": "PepsiCo",
        "industry": "Consumer Goods / Food & Beverage",
        "headcount": 315000,
        "hq": "Purchase, NY",
        "segments": ["Beverages", "Snacks", "Nutrition", "International", "DTC"],
    },
    {
        "id": "ironclad-manufacturing",
        "name": "Ironclad Manufacturing Group",
        "inspired_by": "3M",
        "industry": "Diversified Manufacturing",
        "headcount": 85000,
        "hq": "Saint Paul, MN",
        "segments": ["Safety & Industrial", "Transportation & Electronics", "Healthcare", "Consumer"],
    },
    {
        "id": "horizon-tech",
        "name": "Horizon Technology Solutions",
        "inspired_by": "Accenture",
        "industry": "Technology / IT Services",
        "headcount": 740000,
        "hq": "Dublin, Ireland (US HQ: New York, NY)",
        "segments": ["Strategy & Consulting", "Technology", "Operations", "Industry X", "Song"],
    },
    {
        "id": "pacific-retail",
        "name": "Pacific Retail Holdings",
        "inspired_by": "Target",
        "industry": "Retail",
        "headcount": 400000,
        "hq": "Minneapolis, MN",
        "segments": ["Stores", "Digital", "Supply Chain", "Merchandising", "Marketing"],
    },
    {
        "id": "sterling-pharma",
        "name": "Sterling Life Sciences",
        "inspired_by": "Eli Lilly",
        "industry": "Pharmaceuticals / Biotechnology",
        "headcount": 43000,
        "hq": "Indianapolis, IN",
        "segments": ["Diabetes & Obesity", "Oncology", "Immunology", "Neuroscience", "Manufacturing Expansion"],
    },
    {
        "id": "cascade-utilities",
        "name": "Cascade Power & Utilities",
        "inspired_by": "Duke Energy",
        "industry": "Utilities / Energy",
        "headcount": 28000,
        "hq": "Charlotte, NC",
        "segments": ["Electric Utilities", "Gas Utilities", "Renewables", "Grid Modernization"],
    },
    {
        "id": "vanguard-consulting",
        "name": "Vanguard Professional Services",
        "inspired_by": "Deloitte (self-referential)",
        "industry": "Professional Services",
        "headcount": 450000,
        "hq": "New York, NY",
        "segments": ["Audit & Assurance", "Consulting", "Tax", "Risk Advisory", "Financial Advisory"],
    },
    {
        "id": "liberty-airlines",
        "name": "Liberty Airlines Group",
        "inspired_by": "Delta Air Lines",
        "industry": "Airlines / Aviation",
        "headcount": 95000,
        "hq": "Atlanta, GA",
        "segments": ["Mainline Operations", "Regional", "Cargo", "Loyalty", "MRO"],
    },
    {
        "id": "beacon-media",
        "name": "Beacon Media & Entertainment",
        "inspired_by": "Walt Disney Company",
        "industry": "Media & Entertainment",
        "headcount": 220000,
        "hq": "Burbank, CA",
        "segments": ["Streaming", "Parks & Experiences", "Studios", "Linear Networks", "Consumer Products"],
    },
    {
        "id": "cornerstone-realty",
        "name": "Cornerstone Real Estate Investment",
        "inspired_by": "CBRE Group",
        "industry": "Commercial Real Estate",
        "headcount": 115000,
        "hq": "Dallas, TX",
        "segments": ["Advisory", "Property Management", "Investment Management", "Development", "Workplace Solutions"],
    },
]
